project_id = "zmgkwcsyujpoawdpdnce"

[functions.chat]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.delete-firebase-user]
verify_jwt = false

[functions.list-firebase-users]
verify_jwt = false
